version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgre_focus
    environment:
      POSTGRES_USER: focus
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: focus_library
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
